# Generated by Django 6.0.1 on 2026-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('type', models.CharField(choices=[('RENTAL', 'Rental'), ('CANCELLATION_FEE', 'Cancellation Fee'), ('OVERDUE_FEE', 'Overdue Fee')], max_length=20)),
                ('session_url', models.URLField(max_length=500)),
                ('session_id', models.CharField(max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
