# Generated by Django 6.0.1 on 2026-01-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rental'),
        ),
    ]
