# Generated by Django 6.0.1 on 2026-01-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('rental', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='car.car'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['car', 'start_date', 'end_date'], name='rental_rent_car_id_c80f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='rental_rent_status_1d6559_idx'),
        ),
    ]
