# Generated by Django 6.0.1 on 2026-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=63)),
                ('model', models.CharField(max_length=63)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gas'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric')], max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
