# Generated by Django 6.0.1 on 2026-01-16 17:07

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=car.models.car_image_file_path),
        ),
    ]
